FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*

ARG GOGCLI_VERSION=0.9.0
RUN curl -L https://github.com/steipete/gogcli/releases/download/v${GOGCLI_VERSION}/gogcli_${GOGCLI_VERSION}_linux_amd64.tar.gz \
  | tar -xz -C /usr/local/bin && chmod +x /usr/local/bin/gog
# RUN curl -L https://github.com/steipete/gogcli/releases/download/v${GOGCLI_VERSION}/gogcli_${GOGCLI_VERSION}_linux_amd64.tar.gz \
#   | tar -tzf -
RUN ls /usr/local/bin/gog
# gog needs a config dir for OAuth tokens
# VOLUME ["/home/node/.config/gog"]
ENTRYPOINT ["gog"]
